### PR TITLE
Initial READMe file

### PR DESCRIPTION
**Pull request by stephaniemdavis**
@bgbutler let me know if you get this. I created a new branch named "marine-1"

### CODE REVIEW

**Comment by stephaniemdavis** [comment]
@bgbutler Hi Brian; hope you receive this message. Just testing out the line of communication. TTYL

**Comment by stephaniemdavis** [comment]
@bgbutler 
Hi Brian; just testing out the lines of communication on this site. I created a new Repo called "testbank" and a new branch called "marine-1" (that's the number 1 not the letter "l"). TTYL

**Comment by stephaniemdavis** [comment]
@bgbutler - Correction: the repo is named "testbank". Don't know if I stated this correctly previously. Branch name remains the same.

**Comment by bgbutler** [comment]
Got it - I'll work on uploading over the weekend.

Regards,

Bryan Butler MBA, MS

**Comment by stephaniemdavis** [comment]
OK, good!!!! TTYL

On Wed, Mar 9, 2016 at 5:49 AM bgbutler <notifications@github.com> wrote:

> Got it - I'll work on uploading over the weekend.
>
> Regards,
>
> Bryan Butler MBA, MS
>
> On Tue, Mar 8, 2016 at 10:16 PM, Stephanie M. Davis <
> notifications@github.com> wrote:
>
> > @bgbutler <https://github.com/bgbutler> let me know if you get this. I
> > created a new branch named "marine-1"
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/stephaniemdavis/testbank/pull/1
> > Commit Summary
> >
> > - Initial READMe file
> >
> > File Changes
> >
> > - *M* README.md
> > <https://github.com/stephaniemdavis/testbank/pull/1/files#diff-0> (2)
> >
> > Patch Links:
> >
> > - https://github.com/stephaniemdavis/testbank/pull/1.patch
> > - https://github.com/stephaniemdavis/testbank/pull/1.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/stephaniemdavis/testbank/pull/1>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stephaniemdavis/testbank/pull/1#issuecomment-194238717>
> .
>
-- 
www.linkedin.com/in/stephaniemargodavis

**Comment by bgbutler** [comment]
Hi Stephanie, I have created some of the files from the work at the last meetup. So far, code works for the following:  question numbers (original work), answers (The choice is ), and I am working on the questions.  The regex did not work as planned, so I am trying another route.

**Comment by stephaniemdavis** [comment]
Ok then will check this afternoon

On Tue, Mar 22, 2016, 9:08 PM bgbutler <notifications@github.com> wrote:

> Hi Stephanie, I have created some of the files from the work at the last
> meetup. So far, code works for the following: question numbers (original
> work), answers (The choice is ), and I am working on the questions. The
> regex did not work as planned, so I am trying another route.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/stephaniemdavis/testbank/pull/1#issuecomment-200100560>
>
-- 
www.linkedin.com/in/stephaniemargodavis

**Pull request merged**
